# Generated by Django 3.0.5 on 2020-04-09 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('email', models.CharField(max_length=30, verbose_name='Email')),
                ('phone_number', models.CharField(max_length=12, verbose_name='Phone Number')),
                ('linkedin_url', models.CharField(max_length=60, verbose_name='Linkedin Url')),
                ('total_lines', models.IntegerField(verbose_name='Total No. of Text Lines')),
                ('total_char', models.IntegerField(verbose_name='Total No. of Text characters')),
                ('font_name', models.CharField(max_length=30, verbose_name='Font Name')),
                ('font_size', models.CharField(max_length=30, verbose_name='Font Size')),
                ('total_images', models.IntegerField(verbose_name='Total No. of Images')),
                ('total_tables', models.IntegerField(verbose_name='Total No. of Tables')),
                ('document', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
