# Generated by Django 3.0.5 on 2020-04-09 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='email',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='font_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Font Name'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='font_size',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Font Size'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='linkedin_url',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Linkedin Url'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='total_char',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total No. of Text characters'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='total_images',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total No. of Images'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='total_lines',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total No. of Text Lines'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='total_tables',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total No. of Tables'),
        ),
    ]
