# Generated by Django 3.0.5 on 2020-04-10 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0002_auto_20200409_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='education',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Education'),
        ),
        migrations.AddField(
            model_name='resume',
            name='skills',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Skills'),
        ),
        migrations.AddField(
            model_name='resume',
            name='total_words',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total No. of Text characters'),
        ),
    ]
